//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperZapatos.ProductCatalog.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Store
    {
        public Store()
        {
            this.Articles = new HashSet<Article>();
        }
    
        public int StoreId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Article> Articles { get; set; }
    }
}
